---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  API_ENDPOINT:
  USER: 
  PW: 
  ORG: 
  SPACE: 
  CF_MANIFEST_HOST: attendees

inputs:
  - name: pcf-ers-repo

run:
  path: pcf-ers-repo/ci/tasks/finalize-deploy.sh

